### ISSUE TITLE
首先支持一下。但为何不是针对多文本的计算？

### ISSUE THREAD

**Issue by zbooa** [AbelZhou/PHP-TfIdf#1]
不能理解$res = $transformer->fit_transform($documents[3]);
为何只是计算$documents中的某一个元素的词频，而不是整个数组中所有元素的词频？如果面对多文本数据时候，不可能只针对某一个文本数据来计算词频。如果仅仅计算单一文本的词频，感觉没有意义。不知道是不是我理解有误，希望可以指教一下

**Comment by abelzhou** [comment]
documents是一个文档内容的集合，每一个元素都是一篇文章，
每篇文章的预定关键词都会随着文章总数的不断增加，而不断不断变化。
使用的时候实际上是将新文档加入词频统计范围，然后在计算这个新文档的词频权重找出最合理，匹配的关键词（分类）。

**Comment by zbooa** [comment]
谢谢回复。
第一行字我懂。
第二行我就不懂了，哥们。“随着文章总数的不断增加”，$res = $transformer->fit_transform($documents[3]);？？？？？
这仅仅是一篇文章，集合里的一个元素吧？
我不知道我的理解是不是理解错了，我的理解是用整个集合，所有的文章来算关键词频权重。
现在按我的理解，这代码的确能算出集合里某一个文章，集合里的某一个元素的关键词频权重，但集合里的其它元素，其它文章呢？
for一次吗？然后把权重相加取平均值吗？
我就不知道，如何算多个文章中的词频权重。。。。
如果可必的话，请指教一下
再次谢谢你的回复。
第三行，暂时也理解不了。

在 2018-06-25 09:33:22，"Abel" <notifications@github.com> 写道：


documents是一个文档内容的集合，每一个元素都是一篇文章，
每篇文章的预定关键词都会随着文章总数的不断增加，而不断不断变化。
使用的时候实际上是将新文档加入词频统计范围，然后在计算这个新文档的词频权重找出最合理，匹配的关键词（分类）。

**Comment by abelzhou** [comment]
第二行你的理解没有错。
权重在你塞文档集合的时候已经构建好了
你只需要用fit_transform得到单一文章的词频权重就可以了，这个权重也是综合上面的文档集合产生的。
$documents[3] 只是我偷了一点懒  直接用基础文章当中的某一个文章作为计算的对象
如果你有很多文章都需要分类，那么第一次确实需要for一下，得到每一篇的关键词在整体中的权重。对于第三行而言，如果每天都会产出几十篇文章，每一篇需要及时分类，就需要每新增一篇，就把这篇文章放到文档集合中，然后取一下权重。当然如果可以的话定期也需要整理之前的文章，随着新的文章的不断加入，旧的文章（已经分配好权重的），关键词权重会发生变化。

**Comment by abelzhou** [comment]
通俗易懂一点的解释，只说结果
demo
``` php
$contants = array(
    "我的设计图有点儿问题，我得修改一下。",
    "因为这个比较难看的设计图，她大哭了起来。",
    "老妈命令我把这些过时的衣服处理掉。",
    "幸运的是，爆炸没有造成人员伤亡，老小区的设计图有问题。但是很多人丢掉了衣服。",
    "为了准备这场考试，他花费了大量的时间和精力联系了很多设计图纸。",
    "在公共场合随地吐痰是很粗俗的行为。",
    "杯子装得太满了，果汁都溢出来了，洒到了衣服上。",
    "她趁母亲接电话时偷偷溜出去了。",
    "友谊是从互相信任开始的。"
);
```
这些内容集合中，出现“设计图”的文章较多，而“衣服”的文章较少。
documents[3]中既命中“设计图”，又命中了"衣服"
结果为:"衣服"关键词的权重略高于"设计图"   正是因为与整体有关联
``` php
array(2) {
  [0]=>
  array(5) {
    ["word"]=>
    string(9) "设计图"
    ["count"]=>
    int(1)
    ["tf"]=>
    float(0.5)
    ["idf"]=>
    float(0.58778666490212)
    ["tfidf"]=>
    float(0.29389333245106)
  }
  [1]=>
  array(5) {
    ["word"]=>
    string(6) "衣服"
    ["count"]=>
    int(1)
    ["tf"]=>
    float(0.5)
    ["idf"]=>
    float(0.81093021621633)
    ["tfidf"]=>
    float(0.40546510810816)
  }
}
```

**Comment by zbooa** [comment]
OK。有点头绪。
“fit_transform得到单一文章的词频权重就可以了，这个权重也是综合上面的文档集合产生的。”
这个权重既然是综合上面的文章集合产生。按照您的意思，如果有新增的文章，就要对新增的文章fit_transform一下。
那么问题又来了
对新增的文章，如果是新增了n个文章，
for操作后，每个keyword都会产生不同的TFIDF，这一堆TFIDF数值肯定都不一样，那又怎么能代表“综合上面的文档集合”？
是要取和求平均值还是怎么处理？
再次感谢您的回复和您编写的代码。

在 2018-06-25 13:47:27，"Abel" <notifications@github.com> 写道：


第二行你的理解没有错。
权重在你塞文档集合的时候已经构建好了
你只需要用fit_transform得到单一文章的词频权重就可以了，这个权重也是综合上面的文档集合产生的。
$documents[3] 只是我偷了一点懒 直接用基础文章当中的某一个文章作为计算的对象
如果你有很多文章都需要分类，那么第一次确实需要for一下，得到每一篇的关键词在整体中的权重。对于第三行而言，如果每天都会产出几十篇文章，每一篇需要及时分类，就需要每新增一篇，就把这篇文章放到文档集合中，然后取一下权重。当然如果可以的话定去也需要整理之前的文章，随着新的文章的不断加入，旧的文章（已经分配好权重的），关键词权重会发生变化。

**Comment by abelzhou** [comment]
不需要求和求平均
TFIDF 本质就是在一堆文档中寻找特定文档“独特”的一面。
比如 N篇生活琐事的文章中，新增了一篇有关金融的区块链文章，那么“区块链”关键词作为这篇文章的关键词一定没错，产生的TFIDF也仅仅只适用于这篇文章而已。继续新增其他文章产生的TFIDF和这篇文章已经无关了，有可能新增的文章是“时尚”，“政治”，“街拍”等。

**Comment by zbooa** [comment]
谢谢您的回复。请原谅我的愚笨。
按你这个区块链的例子来说吧，
新增了一篇有关金融的区块链文章，那么“区块链”关键词作为这篇文章的关键词，这个理解，那如果有n篇类似的“区块链”文章呢？这个TFIDF肯定要变吧？
那么，
“fit_transform得到单一文章的词频权重就可以了，这个权重也是综合上面的文档集合产生的。”
如果我使用“区块链”来计算TFIDF值
fit_transform(n) == fit_transform(n+1) 是否为true ?
如果为true，请问针对某一文章计算TFIDF值有何意义？毕竟这TFIDF是综合数值，感觉上参数并无意义。
如果为false，请问造成数值的变化是由于整个文章集合的变化吗？
再次谢谢。

在 2018-06-25 19:41:37，"Abel" <notifications@github.com> 写道：


不需要求和和平均
TFIDF 本质就是在一堆文档中寻找特定文档“独特”的一面。
比如 N篇生活琐事的文章中，新增了一篇有关金融的区块链文章，那么“区块链”关键词作为这篇文章的关键词一定没错，产生的TFIDF也仅仅只适用于这篇文章而已。继续新增其他文章产生的TFIDF和这篇文章已经无关了，有可能新增的文章是“时尚”，“政治”，“街拍”等。

**Comment by abelzhou** [comment]
如果含有某一关键词的文章变多的话，该关键词的权重当然会变。
这也是为啥在上面提到的，有可能你还需要定期重新整理一下你的文章分类。
这里有个误区，并不是每篇文章的关键词都仅仅只有1个，至于有几个不一定，选择哪个在你自己的业务里面。
你的例子里面
fit_transform(n) > fit_transform(n+1)   应该是对的，第二个问题 ：是的

**Comment by zbooa** [comment]
> ?

在 2018-06-26 09:49:18，"Abel" <notifications@github.com> 写道：


如果含有某一关键词的文章变多的话，该关键词的权重当然会变。
这也是为啥在上面提到的，有可能你还需要定期重新整理一下你的文章分类。
这里有个误区，并不是每篇文章的关键词都仅仅只有1个，至于有几个不一定，选择哪个在你自己的业务里面。
你的例子里面
fit_transform(n) > fit_transform(n+1) 应该是对的，第二个问题 ：是的

**Comment by abelzhou** [comment]
再有不懂的话，先看一下TFIDF的一些基本概念。

**Comment by zbooa** [comment]
谢谢。虽然暂时还是有些不理解，还是谢谢耐心的回复。
